<a href="https://colab.research.google.com/github/PrashantAghara/deep-learning-maths/blob/master/gaussian_elimination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
from numpy import array

def test_row_echelon_form(target_function):

    successful_cases = 0
    failed_cases = []

    test_cases = [{'name': 'check_null_matrix',
  'input': {'A': array([[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]),
   'B': array([[0],
          [0],
          [0]])},
  'expected': 'Singular system'},
 {'name': 'check_identity_matrix',
  'input': {'A': array([[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]]),
   'B': array([[0.],
          [0.],
          [0.]])},
  'expected': array([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.]])},
 {'name': 'check_matrix_1',
  'input': {'A': array([[1., 2., 3.],
          [5., 0., 2.],
          [1., 4., 5.]]),
   'B': array([[4.],
          [3.],
          [6.]])},
  'expected': array([[ 1.        ,  2.        ,  3.        ,  4.        ],
         [-0.        ,  1.        ,  1.3       ,  1.7       ],
         [-0.        , -0.        ,  1.        ,  2.33333333]])},
 {'name': 'check_matrix_2',
  'input': {'A': array([[ 1.,  5.,  6.],
          [ 3.,  1.,  4.],
          [ 2., -4., -2.]]),
   'B': array([[ 9.],
          [ 4.],
          [-5.]])},
  'expected': 'Singular system'}]

    successful_cases = 0
    failed_cases = []
    for test_case in test_cases:

        try:
            target_output = target_function(**test_case["input"])
        except Exception as e:
            print("\033[91m", f'An exception was thrown while running your function: {e}.\nInput matrix:\n{test_case["input"]}')
            return


        try:
            if isinstance(test_case['expected'],str):
                assert isinstance(target_output, str)
            else:
                assert np.allclose(target_output, test_case['expected'])
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"],
                    "got": target_output,
                }
            )
            print(
                f"Wrong output for test case {test_case['name']}. \n\tExpected:\n\t {failed_cases[-1].get('expected')}.\n\tGot:\n {failed_cases[-1].get('got')}."
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")


def test_back_substitution(target_function):

    successful_cases = 0
    failed_cases = []

    test_cases = [
        {
            "name": "check_null_matrix",
            "input": np.array(
                    [
                    [1, 0, 0, 5],
                    [0, 1, 0, 6],
                    [0, 0, 1, 7]
                    ]
                ),
            "expected": np.array([5, 6, 7])
        },
        {
            "name": "check_matrix_1",
            "input": np.array([
                [ 1.        ,  2.        ,  3.        ,  4.        ],
                [-0.        ,  1.        ,  1.3       ,  1.7       ],
                [-0.        , -0.        ,  1.        ,  2.33333333]]),
            "expected": np.array([-0.33333333, -1.33333333,  2.33333333])
        },

        {
            "name": "check_matrix_2",
            "input": np.array([
                [ 1.        ,  5.        ,  6.        ,  9.        ],
                [-0.        ,  1.        ,  1.        ,  1.64285714],
                [ 0.        ,  0.        ,  1.        ,  0.        ]]),
            "expected": np.array([0.7857143 , 1.64285714, 0.        ])
        },
        {
            "name": "check_matrix_3",
            "input": np.array([
                [ 1.        ,  8.        ,  6.        ,  9.        ],
                [0.        ,  1        ,  8        ,  6],
                [ 0.        ,  0.        ,  1.        ,  1.        ]]),
            "expected": np.array([19., -2.,  1.])
        }
    ]


    for test_case in test_cases:

        try:
            target_output = target_function(test_case["input"])
        except Exception as e:
            print("\033[91m", f'An exception was thrown while running your function: {e}.\nInput matrix:\n{test_case["input"]}')
            return


        try:
            assert np.allclose(target_output, test_case['expected'])
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"],
                    "got": target_output,
                }
            )
            print(
                f"Wrong output for test case {test_case['name']}. \n\tExpected:\n\t {failed_cases[-1].get('expected')}.\n\tGot:\n {failed_cases[-1].get('got')}."
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")

def test_gaussian_elimination(target_function):

    successful_cases = 0
    failed_cases = []

    test_cases = [{'name': 'test_matrix_0',
  'input': {'A': array([[-9, -1, -5],
          [-9, -9, -8],
          [ 0, -3, -8]]),
   'B': array([[1],
          [4],
          [8]])},
  'expected': array([ 0.44444444,  0.        , -1.        ])},
 {'name': 'test_matrix_1',
  'input': {'A': array([[ 1,  7, -5, -8],
          [ 0, -5, -1,  9],
          [ 6, -6,  0,  5],
          [ 7, -6,  8,  9]]),
   'B': array([[-8],
          [ 4],
          [ 9],
          [ 5]])},
  'expected': array([ 0.0279965 , -2.07567804, -0.14129484, -0.72440945])},
 {'name': 'test_matrix_2',
  'input': {'A': array([[ -9,  -9,  -2,   3, -10],
          [  6,   5,   6,   2,   7],
          [ -6,  -2,   5,   5,   7],
          [ -4,  -5,  -6,  -9,   4],
          [  3,  -6,  -2,  -8,  -8]]),
   'B': array([[ 3],
          [-4],
          [ 1],
          [-2],
          [-3]])},
  'expected': array([-2.24012291,  2.29784899,  1.39727831, -1.46641791, -1.0713345 ])},
 {'name': 'test_matrix_3',
  'input': {'A': array([[ -8,  -9, -10,  -9,   7,  -4],
          [  2,   8,   8,   3,  -8,  -2],
          [ -4,   0,   3,   0,   2,   9],
          [  2,  -6,  -8,  -2,  -8,   9],
          [ -2,  -1,  -3,   3,   4,  -3],
          [-10,   1,  -5,  -6,   3,  -4]]),
   'B': array([[ 1],
          [-6],
          [-4],
          [-1],
          [-1],
          [ 9]])},
  'expected': array([ 1.66947817,  3.32226171, -2.22881748, -1.60512025,  1.48105316,
          0.71136209])},
 {'name': 'test_matrix_4',
  'input': {'A': array([[-10,   8,  -8,  -6,   4,   2,  -2],
          [  3,   1,   6,   2,  -3,  -5, -10],
          [  4,   9,  -9,   1,   2,  -9,  -7],
          [ -2,  -9,   1,   9,   6,  -2,  -2],
          [ -3,  -5, -10,   9,   4,   1, -10],
          [  6,   8,   7,  -3,   6,  -6,   8],
          [  4,  -8,   5,  -4,   1,   3,   6]]),
   'B': array([[ 0],
          [-5],
          [ 2],
          [-6],
          [ 5],
          [ 4],
          [-2]])},
  'expected': array([ 1.28049215,  1.12547489, -0.17505018,  0.74172351,  0.64510371,
          1.98786815, -0.14745546])}]

    for test_case in test_cases:

        try:
            target_output = target_function(**test_case["input"])
        except Exception as e:
            print("\033[91m", f'An exception was thrown while running your function: {e}.\nInput matrix:\n{test_case["input"]}')
            return


        try:
            assert np.allclose(target_output, test_case['expected'])
            successful_cases += 1
        except:
            failed_cases.append(
                {
                    "name": test_case["name"],
                    "expected": test_case["expected"],
                    "got": target_output,
                }
            )
            print(
                f"Wrong output for test case {test_case['name']}. \n\tExpected:\n\t {failed_cases[-1].get('expected')}.\n\tGot:\n {failed_cases[-1].get('got')}."
            )

    if len(failed_cases) == 0:
        print("\033[92m All tests passed")
    else:
        print("\033[92m", successful_cases, " Tests passed")
        print("\033[91m", len(failed_cases), " Tests failed")

In [1]:
from sympy import symbols, Eq, Matrix, solve, sympify
import numpy as np

def string_to_augmented_matrix(equations):
    # Split the input string into individual equations
    equation_list = equations.split('\n')
    equation_list = [x for x in equation_list if x != '']
    # Create a list to store the coefficients and constants
    coefficients = []

    ss = ''
    for c in equations:
        if c in 'abcdefghijklmnopqrstuvwxyz':
            if c not in ss:
                ss += c + ' '
    ss = ss[:-1]

    # Create symbols for variables x, y, z, etc.
    variables = symbols(ss)
    # Parse each equation and extract coefficients and constants
    for equation in equation_list:
        # Remove spaces and split into left and right sides
        sides = equation.replace(' ', '').split('=')

        # Parse the left side using SymPy's parser
        left_side = sympify(sides[0])

        # Extract coefficients for variables
        coefficients.append([left_side.coeff(variable) for variable in variables])

        # Append the constant term
        coefficients[-1].append(int(sides[1]))

    # Create a matrix from the coefficients
    augmented_matrix = Matrix(coefficients)
    augmented_matrix = np.array(augmented_matrix).astype("float64")

    A, B = augmented_matrix[:,:-1], augmented_matrix[:,-1].reshape(-1,1)

    return ss, A, B

In [2]:
import numpy as np

In [4]:
def swap_rows(M, row_index_1, row_index_2):
    """
    Swap rows in the given matrix.

    Parameters:
    - matrix (numpy.array): The input matrix to perform row swaps on.
    - row_index_1 (int): Index of the first row to be swapped.
    - row_index_2 (int): Index of the second row to be swapped.
    """

    # Copy matrix M so the changes do not affect the original matrix.
    M = M.copy()
    # Swap indexes
    M[[row_index_1, row_index_2]] = M[[row_index_2, row_index_1]]
    return M

In [5]:
M = np.array([
[1, 3, 6],
[0, -5, 2],
[-4, 5, 8]
])
print(M)

[[ 1  3  6]
 [ 0 -5  2]
 [-4  5  8]]


In [6]:
M_swapped = swap_rows(M, 0, 2)
print(M_swapped)

[[-4  5  8]
 [ 0 -5  2]
 [ 1  3  6]]


In [7]:
def get_index_first_non_zero_value_from_column(M, column, starting_row):
    """
    Retrieve the index of the first non-zero value in a specified column of the given matrix.

    Parameters:
    - matrix (numpy.array): The input matrix to search for non-zero values.
    - column (int): The index of the column to search.
    - starting_row (int): The starting row index for the search.

    Returns:
    int: The index of the first non-zero value in the specified column, starting from the given row.
                Returns -1 if no non-zero value is found.
    """
    # Get the column array starting from the specified row
    column_array = M[starting_row:,column]
    for i, val in enumerate(column_array):
        # Iterate over every value in the column array.
        # To check for non-zero values, you must always use np.isclose instead of doing "val == 0".
        if not np.isclose(val, 0, atol = 1e-5):
            # If one non zero value is found, then adjust the index to match the correct index in the matrix and return it.
            index = i + starting_row
            return index
    # If no non-zero value is found below it, return -1.
    return -1

In [8]:
N = np.array([
[0, 5, -3 ,6 ,8],
[0, 6, 3, 8, 1],
[0, 0, 0, 0, 0],
[0, 0, 0 ,0 ,7],
[0, 2, 1, 0, 4]
]
)
print(N)
print(get_index_first_non_zero_value_from_column(N, column = 0, starting_row = 0))
print(get_index_first_non_zero_value_from_column(N, column = -1, starting_row = 2))

[[ 0  5 -3  6  8]
 [ 0  6  3  8  1]
 [ 0  0  0  0  0]
 [ 0  0  0  0  7]
 [ 0  2  1  0  4]]
-1
3


In [9]:
def get_index_first_non_zero_value_from_row(M, row, augmented = False):
    """
    Find the index of the first non-zero value in the specified row of the given matrix.

    Parameters:
    - matrix (numpy.array): The input matrix to search for non-zero values.
    - row (int): The index of the row to search.
    - augmented (bool): Pass this True if you are dealing with an augmented matrix,
                        so it will ignore the constant values (the last column in the augmented matrix).

    Returns:
    int: The index of the first non-zero value in the specified row.
                Returns -1 if no non-zero value is found.
    """

    # Create a copy to avoid modifying the original matrix
    M = M.copy()


    # If it is an augmented matrix, then ignore the constant values
    if augmented == True:
        # Isolating the coefficient matrix (removing the constant terms)
        M = M[:,:-1]

    # Get the desired row
    row_array = M[row]
    for i, val in enumerate(row_array):
        # If finds a non zero value, returns the index. Otherwise returns -1.
        if not np.isclose(val, 0, atol = 1e-5):
            return i
    return -1

In [10]:
print(f'Output for row 2: {get_index_first_non_zero_value_from_row(N, 2)}')
print(f'Output for row 3: {get_index_first_non_zero_value_from_row(N, 3)}')

Output for row 2: -1
Output for row 3: 4


In [11]:
def augmented_matrix(A, B):
    """
    Create an augmented matrix by horizontally stacking two matrices A and B.

    Parameters:
    - A (numpy.array): First matrix.
    - B (numpy.array): Second matrix.

    Returns:
    - numpy.array: Augmented matrix obtained by horizontally stacking A and B.
    """
    augmented_M = np.hstack((A,B))
    return augmented_M

In [12]:
A = np.array([[1,2,3], [3,4,5], [4,5,6]])
B = np.array([[1], [5], [7]])

print(augmented_matrix(A,B))

[[1 2 3 1]
 [3 4 5 5]
 [4 5 6 7]]


In [13]:
def row_echelon_form(A, B):
    """
    Utilizes elementary row operations to transform a given set of matrices,
    which represent the coefficients and constant terms of a linear system, into row echelon form.

    Parameters:
    - A (numpy.array): The input square matrix of coefficients.
    - B (numpy.array): The input column matrix of constant terms

    Returns:
    numpy.array: A new augmented matrix in row echelon form with pivots as 1.
    """

    # Before any computation, check if matrix A (coefficient matrix) has non-zero determinant.
    # It will be used the numpy sub library np.linalg to compute it.

    det_A = np.linalg.det(A)

    # Returns "Singular system" if determinant is zero
    if np.isclose(det_A, 0) == True:
        return 'Singular system'

    # Make copies of the input matrices to avoid modifying the originals
    A = A.copy()
    B = B.copy()


    # Convert matrices to float to prevent integer division
    A = A.astype('float64')
    B = B.astype('float64')

    # Number of rows in the coefficient matrix
    num_rows = len(A)

    ### START CODE HERE ###

    # Transform matrices A and B into the augmented matrix M
    M = augmented_matrix(A,B)

    # Iterate over the rows.
    for row in range(num_rows):

        # The first pivot candidate is always in the main diagonal, let's get it.
        # Remember that the diagonal elements in a matrix has the same index for row and column.
        # You may access a matrix value by typing M[row, column]. In this case, column = None
        pivot_candidate = M[row, row]

        # If pivot_candidate is zero, it cannot be a pivot for this row.
        # So the first step you need to take is to look at the rows below it to check if there is a non-zero element in the same column.
        # The usage of np.isclose is a good practice when comparing two floats.
        if np.isclose(pivot_candidate, 0) == True:
            # Get the index of the first non-zero value below the pivot_candidate.
            first_non_zero_value_below_pivot_candidate = get_index_first_non_zero_value_from_column(M, row, row)

            # Swap rows
            M = swap_rows(M, row, first_non_zero_value_below_pivot_candidate)

            # Get the pivot, which is in the main diagonal now
            pivot = M[row,row]

        # If pivot_candidate is already non-zero, then it is the pivot for this row
        else:
            pivot = pivot_candidate

        # Now you are ready to apply the row reduction in every row below the current

        # Divide the current row by the pivot, so the new pivot will be 1. You may use the formula current_row -> 1/pivot * current_row
        # Where current_row can be accessed using M[row].
        M[row] = (1/pivot) * M[row]

        # Perform row reduction for rows below the current row
        for j in range(row + 1, num_rows):
            # Get the value in the row that is below the pivot value.
            # Remember that, since you are dealing only with non-singular matrices, the pivot is in the main diagonal.
            # Therefore, the values in row j that are below the pivot, must have column index the same index as the column index for the pivot.
            value_below_pivot = M[j,row]

            # Perform row reduction using the formula:
            # row_to_reduce -> row_to_reduce - value_below_pivot * pivot_row
            M[j] = M[j] - value_below_pivot*M[row]

    ### END CODE HERE ###

    return M

In [14]:
A = np.array([[1,2,3],[0,1,0], [0,0,5]])
B = np.array([[1], [2], [4]])
row_echelon_form(A,B)

array([[1. , 2. , 3. , 1. ],
       [0. , 1. , 0. , 2. ],
       [0. , 0. , 1. , 0.8]])

In [15]:
def back_substitution(M):
    """
    Perform back substitution on an augmented matrix (with unique solution) in reduced row echelon form to find the solution to the linear system.

    Parameters:
    - M (numpy.array): The augmented matrix in row echelon form with unitary pivots (n x n+1).

    Returns:
    numpy.array: The solution vector of the linear system.
    """

    # Make a copy of the input matrix to avoid modifying the original
    M = M.copy()

    # Get the number of rows (and columns) in the matrix of coefficients
    num_rows = M.shape[0]

    ### START CODE HERE ####

    # Iterate from bottom to top
    for row in reversed(range(num_rows)):
        substitution_row = M[row]

        # Get the index of the first non-zero element in the substitution row. Remember to pass the correct value to the argument augmented.
        index = get_index_first_non_zero_value_from_row(M, row)

        # Iterate over the rows above the substitution_row
        for j in range(row):

            # Get the row to be reduced. The indexing here is similar as above, with the row variable replaced by the j variable.
            row_to_reduce = M[j]

            # Get the value of the element at the found index in the row to reduce
            value = row_to_reduce[index]

            # Perform the back substitution step using the formula row_to_reduce -> row_to_reduce - value * substitution_row
            row_to_reduce = row_to_reduce - value * substitution_row

            # Replace the updated row in the matrix, be careful with indexing!
            M[j,:] = row_to_reduce

    ### END CODE HERE ####

     # Extract the solution from the last column
    solution = M[:,-1]

    return solution


In [16]:
test_back_substitution(back_substitution)

 All tests passed


In [17]:
def gaussian_elimination(A, B):
    """
    Solve a linear system represented by an augmented matrix using the Gaussian elimination method.

    Parameters:
    - A (numpy.array): Square matrix of size n x n representing the coefficients of the linear system
    - B (numpy.array): Column matrix of size 1 x n representing the constant terms.

    Returns:
    numpy.array or str: The solution vector if a unique solution exists, or a string indicating the type of solution.
    """

    ### START CODE HERE ###

    # Get the matrix in row echelon form
    row_echelon_M = row_echelon_form(A,B)

    # If the system is non-singular, then perform back substitution to get the result.
    # Since the function row_echelon_form returns a string if there is no solution, let's check for that.
    # The function isinstance checks if the first argument has the type as the second argument, returning True if it does and False otherwise.
    if not isinstance(row_echelon_M, str):
        solution = back_substitution(row_echelon_M)

    ### END SOLUTION HERE ###

    return solution

In [18]:
test_gaussian_elimination(gaussian_elimination)

 All tests passed


In [19]:
equations = """
3*x + 6*y + 6*w + 8*z = 1
5*x + 3*y + 6*w = -10
4*y - 5*w + 8*z = 8
4*w + 8*z = 9
"""

variables, A, B = string_to_augmented_matrix(equations)

sols = gaussian_elimination(A, B)

if not isinstance(sols, str):
    for variable, solution in zip(variables.split(' '),sols):
        print(f"{variable} = {solution:.4f}")
else:
    print(sols)

x = -1.5414
y = -0.5223
w = -0.1210
z = 1.1855
