In [1]:
import numpy as np

#### Ways to create arrays in Numpy

In [2]:
arr = np.array([10, 12])
print(arr)

[10 12]


In [3]:
arr2 = np.arange(3)
print(arr2)

[0 1 2]


In [4]:
arr3 = np.arange(1, 20, 3)
print(arr3)

[ 1  4  7 10 13 16 19]


In [7]:
arr4 = np.linspace(0, 100, 5)
print(arr4)

arr4_int = np.linspace(0, 100, 5, dtype=int)
print(arr4_int)

[  0.  25.  50.  75. 100.]
[  0  25  50  75 100]


In [9]:
char_arr = np.array("Prashant Aghara")
print(char_arr)
print(char_arr.dtype)

Prashant Aghara
<U15


In [13]:
print(np.ones(3))
print(np.zeros(3))
print(np.empty(3))
print(np.random.rand(3))

[1. 1. 1.]
[0. 0. 0.]
[0. 0. 0.]
[0.30665689 0.56353745 0.19625696]


#### 2D Array

In [15]:
two_d_arr = np.array([[1,2,3],[4,5,6]])
print(two_d_arr)

[[1 2 3]
 [4 5 6]]


In [16]:
one_dim_arr = np.array([1,2,3,4,5,6])

multi_dim_arr = np.reshape(one_dim_arr, (2,3))
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]
