In [1]:
import numpy as np

#### Ways to create arrays in Numpy

In [2]:
arr = np.array([10, 12])
print(arr)

[10 12]


In [3]:
arr2 = np.arange(3)
print(arr2)

[0 1 2]


In [4]:
arr3 = np.arange(1, 20, 3)
print(arr3)

[ 1  4  7 10 13 16 19]


In [7]:
arr4 = np.linspace(0, 100, 5)
print(arr4)

arr4_int = np.linspace(0, 100, 5, dtype=int)
print(arr4_int)

[  0.  25.  50.  75. 100.]
[  0  25  50  75 100]


In [9]:
char_arr = np.array("Prashant Aghara")
print(char_arr)
print(char_arr.dtype)

Prashant Aghara
<U15


In [13]:
print(np.ones(3))
print(np.zeros(3))
print(np.empty(3))
print(np.random.rand(3))

[1. 1. 1.]
[0. 0. 0.]
[0. 0. 0.]
[0.30665689 0.56353745 0.19625696]


#### 2D Array

In [15]:
two_d_arr = np.array([[1,2,3],[4,5,6]])
print(two_d_arr)

[[1 2 3]
 [4 5 6]]


In [16]:
one_dim_arr = np.array([1,2,3,4,5,6])

multi_dim_arr = np.reshape(one_dim_arr, (2,3))
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


#### Finding Shape & Size of array

In [19]:
one_dim_arr.ndim

1

In [20]:
multi_dim_arr.shape

(2, 3)

In [21]:
multi_dim_arr.size

6

#### Math Operations

In [22]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

addition = arr1 + arr2
print(addition)

subtraction = arr1 - arr2
print(subtraction)

multiplication = arr1 * arr2
print(multiplication)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


#### Indexing & Slicing

In [23]:
arr = np.array([1,2,3,4,5,6])

print(arr[3])

4


In [25]:
two_dim = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(two_dim[2][2])

print(two_dim[2])

9
[7 8 9]


In [37]:
# SLICING
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:4])
print(arr[:3])
print(arr[2:])
print(arr[::3])
print(arr == arr[::])
print(two_dim[0:2])
print(two_dim[1:3])
print(two_dim[:,2])

[2 3 4]
[1 2 3]
[3 4 5 6 7]
[1 4 7]
[ True  True  True  True  True  True  True]
[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]
[3 6 9]


#### Stacking

In [38]:
a1 = np.array([[1,1],
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [39]:
vert_stack = np.vstack((a1, a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [40]:
hori_stack = np.hstack((a1, a2))
print(hori_stack)

[[1 1 3 3]
 [2 2 4 4]]
